name: Tier 3 - Daily Financial Data

on:
  schedule:
    # Runs daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-financial-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify encrypted environment setup
      env:
        ENV_ENCRYPTION_KEY: ${{ secrets.ENV_ENCRYPTION_KEY }}
      run: |
        echo "Verifying encrypted environment setup..."
        
        # Check if encryption key is available
        if [ -z "$ENV_ENCRYPTION_KEY" ]; then
          echo "ERROR: ENV_ENCRYPTION_KEY not found in secrets"
          exit 1
        fi
        
        # Check if encrypted file exists
        if [ ! -f ".env.encrypted" ]; then
          echo "ERROR: .env.encrypted file not found"
          exit 1
        fi
        
        echo "✓ Encryption key available"
        echo "✓ Encrypted file found"
        
    - name: Run Tier 3 data collection
      run: python collect_tier3.py
      env:
        # Encryption key for .env file
        ENV_ENCRYPTION_KEY: ${{ secrets.ENV_ENCRYPTION_KEY }}
        
    - name: Log completion
      run: echo "Tier 3 financial data collection completed at $(date)"

