name: Tier 2 - Worker Data Collection

on:
  schedule:
    # Runs every hour at 15 minutes past the hour
    - cron: '15 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  collect-worker-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify encrypted environment setup
      env:
        ENV_ENCRYPTION_KEY: ${{ secrets.ENV_ENCRYPTION_KEY }}
      run: |
        echo "Verifying encrypted environment setup..."
        
        # Check if encryption key is available
        if [ -z "$ENV_ENCRYPTION_KEY" ]; then
          echo "ERROR: ENV_ENCRYPTION_KEY not found in secrets"
          exit 1
        fi
        
        # Check if encrypted file exists
        if [ ! -f ".env.encrypted" ]; then
          echo "ERROR: .env.encrypted file not found"
          exit 1
        fi
        
        echo "✓ Encryption key available"
        echo "✓ Encrypted file found"
        
    - name: Run Tier 2 data collection
      run: python collect_tier2.py
      env:
        # Encryption key for .env file
        ENV_ENCRYPTION_KEY: ${{ secrets.ENV_ENCRYPTION_KEY }}
        
    - name: Log completion
      run: echo "Tier 2 worker data collection completed at $(date)"

